language: python

cache: pip
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
      - libgeos-c1
      - libxml2-dev

before_script:
  - flake8 registry.py
  - pycsw-admin.py -c get_sysprof

install:
  - pip install -r requirements.txt
  - pip install -r testing.txt

script:
  - coverage run --source=registry test_registry.py

after_success:
  - coveralls
