language: python

cache: pip
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
      - libgeos-c1
      - libxml2-dev

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py -q install

before_script:
  - python registry.py pycsw -c get_sysprof
  - python registry.py pycsw -c setup_db

script:
  - coverage run --source=registry setup.py test

after_script:
  - flake8 registry.py

after_success:
  - coveralls
