language: python

cache: pip
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.5"

env:
  - VERSION=5.0
  - VERSION=1.7

addons:
  apt:
    sources:
      - elasticsearch-$VERSION
    packages:
      - libgeos-c1
      - libxml2-dev
      - elasticsearch
      - python-flake8

service:
  - elasticsearch

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py -q install

before_script:
  - python registry.py pycsw -c get_sysprof
  - python registry.py pycsw -c setup_db


script:
  - coverage run --source=registry setup.py test

after_script:
  - flake8 registry.py

after_success:
  - coveralls
