language: python

cache: pip
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
      - libgeos-c1
      - libxml2-dev

install:
  - pip install -r requirements.txt
  - python setup.py -q install

before_script:
  - pycsw-admin.py -c get_sysprof

script:
  - coverage run --source=registry setup.py test

after_script:
  - flake8 registry.py

after_success:
  - coveralls
