version: '2'
services:

  elasticsearch:
   image: terranodo/elasticsearch

  django:
    build: .
    volumes:
      - '.:/code/'
    environment:
    - REGISTRY_SEARCH_URL=http://elasticsearch:9200/

  angular:
    image: terranodo/search
    command: "npm run server"
    ports:
      - "3001:3001"

  maploom:
    image: terranodo/maploom
    command: grunt serve

  nginx:
    image: geonode/nginx:registry
    links:
      - django
      - maploom
      - elasticsearch
    ports:
      - "80:80"
